#!/bin/bash
PATH=/bin:/sbin:/usr/bin:/usr/sbin

echo  -e "Content-type: text/html \n\n"
echo "<html>"
echo "<head>"
echo "<title>网络设置</title>"
echo "<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />"
echo "</head>"
echo "<body>"
echo "<center>"
echo "<h3>网络设置</h3>"
echo "</center>"
echo "<hr>"
    echo "<center>"
    echo "<form action=\"/cgi-bin/donetworking.cgi\" method=POST>"
    echo "<table width=\"75%\">"
         echo  "<tr>"
                echo "<td>IP地址</td>"
                echo "<td><input type=\"text\" name=\"ipaddr\"/></td>"
                echo "<td>例如:192.168.1.150</td>"
         echo "</tr>"
         echo "<tr>"
                echo "<td>子网掩码</td>"
                echo "<td><input type=\"text\" name=\"netmask\"/></td>"
                echo "<td>例如:24</td>"
         echo "</tr>"
         echo "<tr>"
                echo "<td>网关地址</td>"
                echo "<td><input type=\"text\" name=\"gateway\"/></td>"
                echo "<td>例如:192.168.1.254</td>"
         echo "</tr>"
         echo "<tr>"
                echo "<td><input type=\"submit\" value=\"提交\"></td>"
                echo "<td><input type=\"reset\" name=\"重置\"/></td>"
         echo "</tr>"
    echo "</table>"
   echo "</form>"
    echo "</center>"
echo "</body>"
echo -e "</html>\n\n"
 
