#!/bin/bash
PATH=/bin:/sbin:/usr/bin:/usr/sbin

CURTIME=`hwclock -r  | date '+%Y/%m/%d %X'`

echo  -e "Content-type: text/html \n\n"
echo "<html>"
echo "<head>"
echo "<title>时间设置</title>"
echo "<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />"
echo "</head>"
echo "<body>"
echo "<center>"
echo "<h3>系统时间设置</h3>"
echo "</center>"
echo "<hr>"
    echo "<center>"
    echo "<br><br>"
    echo "<form name=\"time\" action=\"/cgi-bin/dosystime.cgi\" method=POST>"
    echo "<table>"
        echo "<tr>"
            echo "<td>当前硬件时间：<td>"
            echo "<td>\"${CURTIME}\"</td>"
        echo "</tr>"
        echo "<tr>"
            echo "<td><br><td>"
        echo "</tr>"
        echo "<tr>"
            echo "<td>日期：<td>"
            echo "<td><input type=\"text\" name=\"day\" maxlength=\"10\" ></td>"
            echo "<td>(格式：YYYY-MM-DD)<td>"
        echo "</tr>"
        echo "<tr>"
            echo "<td>时间：<td>"
            echo "<td><input type=\"text\" name=\"time\" maxlength=\"5\" ></td>"
            echo "<td>(格式：hh:mm)<td>"
        echo "</tr>"
        echo "<tr>"
            echo "<td>&nbsp;<td>"
            echo "<td><input type=\"submit\" name=\"update\" value=\"更改\" ></td>"
        echo "</tr>"
    echo "</table>"
    echo "</form>"
    echo "</center>"
echo "</body>"
echo "</html>"

